<?php if (! defined('ABSPATH')) exit; // Exit if accessed directly
$config = array(
	'resource'	=> 'star-empty',
	'report'	=> 'chart-bar',
	// 'calendar'	=> 'grid',
	// 'calendar'	=> 'check',
	// 'date'		=> 'calendar',
	// 'time'		=> 'clock',
	// 'shift'		=> 'clock',
	// 'shift'		=> 'work',
	// 'break'		=> 'coffee',
	// 'timeoff'	=> 'reply',
	// 'user'		=> 'user',
	// 'users'		=> 'users',
	// 'location'	=> 'home',
	// 'trade'		=> 'exchange',
	// 'trade'		=> 'refresh',
	// 'conflict'	=> 'exclamation',
	// 'comment'	=> 'comment',
	);
